### ISSUE TITLE
Verify working providers

### ISSUE THREAD

**Issue by disprosium8** [fabric-testbed/fabfed#131]
- [x] FABRIC
- [x] Cloudlab (see #129)
- [x] Chameleon (TACC is OK, but STAR may be out of floating IPs)
- [ ] GCP (provisions but no dataplane peering/ping, see #113)
- [ ] AWS
- [x] SENSE-AWS (outstanding issue with AWS destroy (detach), unrelated to FabFed, see #112)
- [ ] SENSE-GCP (provisions but no dataplane peering/ping, see #113)
- [x] Janus (see #128)
